/** A dependency-free local dashboard served by the API process. */
export const dashboardHtml = `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Meraki Studio</title><style>
:root{color-scheme:dark;--bg:#09111f;--panel:#111d30;--line:#243651;--text:#edf4ff;--muted:#91a4c2;--accent:#5eead4;--purple:#a78bfa;--bad:#fb7185}*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 85% 0,#172554 0,transparent 35%),var(--bg);color:var(--text);font:14px/1.5 system-ui,sans-serif}main{max-width:1240px;margin:auto;padding:28px}header,.auth,.row{display:flex;align-items:center;gap:12px}header{justify-content:space-between;margin-bottom:24px}h1{margin:0;font-size:27px}h1 span{color:var(--accent)}.auth{flex-wrap:wrap}input{width:300px;max-width:55vw;background:#08101d;border:1px solid var(--line);border-radius:8px;color:var(--text);padding:10px}button{cursor:pointer;border:0;border-radius:8px;background:var(--accent);color:#04201c;font-weight:700;padding:10px 14px}button.secondary{background:#263752;color:var(--text)}.status{color:var(--muted)}.grid{display:grid;grid-template-columns:repeat(4,1fr);gap:14px}.card,.panel{background:color-mix(in srgb,var(--panel) 94%,transparent);border:1px solid var(--line);border-radius:12px;padding:18px;box-shadow:0 14px 35px #0003}.card strong{display:block;font-size:30px}.card span,th,.muted{color:var(--muted)}.panels{display:grid;grid-template-columns:1fr 1fr;gap:14px;margin-top:14px}.panel.wide{grid-column:1/-1}h2{font-size:16px;margin:0 0 14px}.bar-row{display:grid;grid-template-columns:95px 1fr 35px;gap:8px;align-items:center;margin:10px 0}.track{height:9px;background:#263752;border-radius:9px;overflow:hidden}.fill{height:100%;background:linear-gradient(90deg,var(--accent),var(--purple));border-radius:9px}table{border-collapse:collapse;width:100%}th,td{text-align:left;padding:9px 8px;border-bottom:1px solid var(--line);vertical-align:top}.claim{max-width:470px}.pill{display:inline-block;border:1px solid var(--line);border-radius:99px;padding:2px 8px;color:var(--accent)}.empty{padding:25px;text-align:center;color:var(--muted)}.error{color:var(--bad)}@media(max-width:800px){main{padding:16px}.grid{grid-template-columns:1fr 1fr}.panels{grid-template-columns:1fr}.panel.wide{grid-column:auto}.auth{align-items:stretch}header{align-items:flex-start;flex-direction:column}input{width:100%;max-width:none}.scroll{overflow:auto}}
</style></head><body><main><header><div><h1>Meraki <span>Studio</span></h1><div class="status">Evidence-backed learning activity</div></div><div class="auth"><input id="token" type="password" autocomplete="off" placeholder="Bearer token"><button id="connect">Connect</button><button id="refresh" class="secondary">Refresh</button></div></header>
<div id="message" class="status">Enter a local API token to inspect this subject.</div><section class="grid" id="metrics"></section><section class="panels"><article class="panel"><h2>Evaluation results</h2><div id="evaluations"></div></article><article class="panel"><h2>Knowledge state</h2><div id="states"></div></article><article class="panel wide"><h2>Profile atoms</h2><div class="scroll" id="atoms"></div></article><article class="panel wide"><h2>Recent runs</h2><div class="scroll" id="runs"></div></article></section>
</main><script>
const q=(s)=>document.querySelector(s), esc=(v)=>String(v??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const endpoints=['profile/atoms','runs','update-proposals','evaluations']; let model={};
async function api(path,options={}){const token=q('#token').value.trim();const r=await fetch('/v1/'+path,{...options,headers:{'content-type':'application/json',authorization:'Bearer '+token,...options.headers}});const body=await r.json().catch(()=>({}));if(!r.ok)throw new Error(body.error||('HTTP '+r.status));return body}
const bars=(entries)=>{const max=Math.max(1,...entries.map(x=>x[1]));return entries.length?entries.map(([name,n])=>'<div class="bar-row"><span>'+esc(name)+'</span><div class="track"><div class="fill" style="width:'+(n/max*100)+'%"></div></div><b>'+n+'</b></div>').join(''):'<div class="empty">No data yet</div>'};
function render(){const atoms=model.atoms||[],runs=model.runs||[],proposals=model.proposals||[],evaluations=model.evaluations||[];q('#metrics').innerHTML=[['Runs',runs.length],['Profile atoms',atoms.length],['Pending reviews',proposals.filter(x=>x.status==='pending').length],['Evaluations',evaluations.length]].map(x=>'<div class="card"><span>'+x[0]+'</span><strong>'+x[1]+'</strong></div>').join('');const count=(xs,key)=>Object.entries(xs.reduce((a,x)=>(a[x[key]||'unknown']=(a[x[key]||'unknown']||0)+1,a),{}));q('#states').innerHTML=bars(count(atoms,'lifecycle'));q('#evaluations').innerHTML=bars(count(evaluations.map(x=>x.evaluation||{}),'result'));q('#atoms').innerHTML=atoms.length?'<table><thead><tr><th>Claim</th><th>Facet</th><th>State</th><th>Confidence</th><th>Action</th></tr></thead><tbody>'+atoms.map(a=>'<tr><td class="claim">'+esc(a.claim)+'</td><td>'+esc(a.facet)+'</td><td><span class="pill">'+esc(a.lifecycle)+'</span></td><td>'+esc(a.confidence)+'</td><td>'+(a.lifecycle==='candidate'?'<button data-approve="'+esc(a.id)+'" data-version="'+esc(a.version)+'">Approve</button>':'—')+'</td></tr>').join('')+'</tbody></table>':'<div class="empty">No learned profile atoms yet</div>';q('#runs').innerHTML=runs.length?'<table><thead><tr><th>Run</th><th>Task type</th><th>Guidance used</th><th>Output</th></tr></thead><tbody>'+runs.slice().reverse().slice(0,20).map(r=>'<tr><td>'+esc(r.run?.trace?.runId)+'</td><td>'+esc(r.context?.task_type)+'</td><td>'+esc(r.run?.trace?.appliedAtomIds?.length??0)+'</td><td class="claim">'+esc(r.run?.output||r.run?.baseline)+'</td></tr>').join('')+'</tbody></table>':'<div class="empty">No agent runs yet</div>'}
async function load(){q('#message').textContent='Loading…';q('#message').className='status';try{const [atoms,runs,proposals,evaluations]=await Promise.all(endpoints.map(api));model={atoms:atoms.items,runs:runs.items,proposals:proposals.items,evaluations:evaluations.items};render();q('#message').textContent='Live snapshot · '+new Date().toLocaleTimeString()}catch(e){q('#message').textContent='Could not load dashboard: '+e.message;q('#message').className='status error'}}
q('#connect').onclick=load;q('#refresh').onclick=load;q('#token').onkeydown=e=>{if(e.key==='Enter')load()};q('#atoms').onclick=async e=>{const b=e.target.closest('[data-approve]');if(!b)return;b.disabled=true;try{await api('profile/atoms/'+encodeURIComponent(b.dataset.approve)+'/commands',{method:'POST',body:JSON.stringify({atom_id:b.dataset.approve,expected_version:Number(b.dataset.version),operation:'confirm'})});await load()}catch(err){q('#message').textContent='Approval failed: '+err.message;q('#message').className='status error';b.disabled=false}};
</script></body></html>`;
